---
- name: bootstrap Python 2.x for new OS
  hosts: tag_Role_mongodb
  remote_user: ubuntu
  become: yes
  gather_facts: no

  tasks:
    - debug: msg="Working on init logstash instance"
    - raw: "if ! which python2.7; then apt-get update -qqy && apt-get install -y python; fi"

- name: work on host mongodb server
  hosts: tag_Role_mongodb
  remote_user: ubuntu
  become: yes
  gather_facts: yes

  vars_files:
    - vars/common.yml

  roles:
    - mongodb-install
    - nodejs6-install
